spring:
  datasource:
    url: jdbc:mysql://localhost:3306/inn_prod
    username: inn_prod_user
    password: Shalom.shalom00
    platform: mysql
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: false
