INSERT INTO category (description) VALUES ('American');
INSERT INTO category (description) VALUES ('Italian');
INSERT INTO category (description) VALUES ('Mexican');
INSERT INTO category (description) VALUES ('Fast Food');
INSERT INTO unit_of_measure (unit) VALUES ('Each');
INSERT INTO unit_of_measure (unit) VALUES ('Tspn');
INSERT INTO unit_of_measure (unit) VALUES ('Tbsp');
INSERT INTO unit_of_measure (unit) VALUES ('Cup');
INSERT INTO unit_of_measure (unit) VALUES ('Dash');
INSERT INTO unit_of_measure (unit) VALUES ('Ounce');